### ISSUE TITLE
Person who decreases bus should be notified 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#102]
This isn't necessary or a main focus for the Buffett Bus in less then two weeks, but is a side note from the feedback of these trips. 

My buddy Mody was the 41st person to sign up, reducing the cost. He should be notified that he reduced the cost per person for everyone on the bus

![11853856_10154098981262598_1724590258_n](https://cloud.githubusercontent.com/assets/11848699/9179397/da819be4-3f61-11e5-9d1b-dac3ce7b025b.jpg)

**Comment by markstm17** [comment]
![11857556_10154098981482598_838107671_n](https://cloud.githubusercontent.com/assets/11848699/9179400/e72ce7b8-3f61-11e5-9ac5-0decd2a7e811.jpg)

**Comment by freindst** [comment]
I can change the email notification, and make people receive content different.

**Comment by markstm17** [comment]
This is NOT a huge priority right now @freindst , unless it is really easy to work with and integrate and implement. 

0-10
11-20
21-30
31-40
41-50


There are 4 people (At the 11th, 21st, 31st, 41st) that ultimately tip the scale and change the price for the overall group, at that point in time after they signed up. Can we either notify them that THEY changed the price from $X to $Y or can we at least give them the same confirmation email that everyone else has gotten. They say the price at $X and now it is at $Y.


Does this make sense @duncangraham and @freindst ?

**Comment by freindst** [comment]
1. For example. There are 20 people already in the trip. If the 21th one joins the trip, it is possible to send a special email to the 21th user in the trip with our model right now. (e.g. Your pledge decreased the price of the trip from xxx to yyy.)
 2. Still based on the example above, as we are not tracking the passenger order, unless I add another table (which might come true in future), we cannot tell who the 11th user is with our current system.

**Comment by markstm17** [comment]
We know who the 11th user is when the 11th user pledges. At that point the price will drop. We don't necessarily care who the 11th user is when the 21st user pledges.

Either way, lets come back to this ticket/issue after this first trip, it is not that important right now @freindst

**Comment by freindst** [comment]
I have implemented it. User who drops the trip price after pledging will get a special email notification.
![image](https://cloud.githubusercontent.com/assets/13219475/9258418/0e696fb6-41c1-11e5-9074-d48ecf14192a.png)
