### ISSUE TITLE
Number of Users matching number of people signed up

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#105]
![screen shot 2015-08-10 at 1 34 20 pm](https://cloud.githubusercontent.com/assets/11848699/9181804/aad61a4a-3f6c-11e5-840e-d27b0abe1e16.png)

@freindst I know that I mentioned this in another issue, but I couldn't find it. It says there are 42 people signed up, but there are only 41 people actually signed up.

**Comment by markstm17** [comment]
Does that mean it is on the 42nd person? "Current passenger Number"

**Comment by freindst** [comment]
It is a bug, but I cannot tell why right now. These are two different data references.

**Comment by markstm17** [comment]
@freindst please update me when this is fixed tomorrow

**Comment by freindst** [comment]
fixed
