### ISSUE TITLE
New Price in Subject Line

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#106]
![11855445_10154100025682598_973858625_n](https://cloud.githubusercontent.com/assets/11848699/9186785/a8693734-3f8e-11e5-978c-9e2c014d74e1.jpg)

What are your thoughts on this @duncangraham and @freindst ??

**Comment by freindst** [comment]
We can have a discuss on the message format. What subject, what content. Or let user choose different templates
