### ISSUE TITLE
move app to https

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#110]
We should move the app to https before we ask people to provide credit card info. Even though we're working with braintree and security shouldn't be an issue, this is still something we need to do eventually.

**Comment by freindst** [comment]
Here are some materials I have read:
 - [Secure your site with HTTPS](https://support.google.com/webmasters/answer/6073543?hl=en)
 - [What is HTTPS - Why Secure a Web Site](http://webdesign.about.com/od/ecommerce/a/aa070407.htm)
 - [The Cheapest SSL Certificates](http://webdesign.about.com/od/ssl/tp/cheapest-ssl-certificates.htm)
 - [How To Create a Self-Signed SSL Certificate](http://webdesign.about.com/od/ssl/tp/cheapest-ssl-certificates.htm)

I think we may follow these steps:
 1. create a self-signed ssl, and test how to apply it on our website/server
 2. get a free SSL certification from a 3rd provide, and make sure everything works
 3. choose a affordable SSL CA, and implemented on our site.
We should discuss it together and generate a common idea.

**Comment by duncangraham** [comment]
moving forward with https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority in the morning

**Comment by markstm17** [comment]
I've got to learn how to merge issues when we repeat them.

This is same as #97

**Comment by duncangraham** [comment]
THIS HAPPENED! 

<img width="283" alt="screen shot 2015-08-13 at 12 40 14 pm" src="https://cloud.githubusercontent.com/assets/865298/9259811/b3da5fb8-41b8-11e5-9f2c-32fe21c4876d.png">



Also, @markstm17 in the future feel free to police and shut down duplicate tickets.

**Comment by freindst** [comment]
cool
