### ISSUE TITLE
User acquisition strategies

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#114]
Let's use this ticket to post user acquisition strategies. If you come up with an idea, edit this post with your name and idea. As we prioritize ideas we can add the relevant github ticket numbers by the associated ideas here.

### Trev
- [ ] if it's the month of your birthday, the buses are on Argo.

### Duncan
- [ ] a full bus should reward the passengers substantially
- [ ] inviting a certain amount of friends to a bus (3-5 or so) should make your ticket free

**Comment by markstm17** [comment]
Going to transfer over to ArgoBus @duncangraham
