### ISSUE TITLE
Partnerships Master Quest

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#119]
Right now we're working with First Student, but it isn't a true partnership (with them working with our software). Let use this ticket to list bus companies and our relationships with them. Discuss progress in individual partner tickets, and update this comment with current status for each company as well as some stats on each company (size, locations, bus fleet info, etc).

**Comment by markstm17** [comment]
Just made a new repo on ArgoBus for this

**Comment by duncangraham** [comment]
cool
