### ISSUE TITLE
Shows list of people who have Pledged/Committed/Signed up for bus visible to others

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#12]
@duncangraham and @freindst 

What are your thoughts with this? 

Either way we are going to NEED a way for the admin and organizer side to have a list of the group of people on each particular bus, but should we allow the entire group to view that as well? I think it could be a selling point (Seeing your friends on a particular bus through social media)

**Comment by markstm17** [comment]
Admin and Organizer view-ability is needed for the Dave concert Trip on the 25th

**Comment by markstm17** [comment]
![11759542_10154023080027598_665921346_n](https://cloud.githubusercontent.com/assets/11848699/8686751/ba40fec4-2a4e-11e5-8af7-ef41a359f027.jpg)

**Comment by freindst** [comment]
I think the names should be limited to view by organizer and administrator. No one wants their trip being known by unfamiliar people.
What I mean is if someone wants to have his/her friends know the trip, he/she shall actively post the information on social media. If such trip is public to anyone, it seems that everyone can trace this guy.

**Comment by duncangraham** [comment]
yea I'd agree with @freindst: the full list of names should only be available to the admin and the organizer. 

I could imagine facebook integration which would let you know how many of your friends (and possibly which friends) were pledged to go on a bus. That would come down to each users privacy settings probably and doesn't seem as high priority as some other tasks

**Comment by freindst** [comment]
legacy problem.
After pledging, user shall see a list of all user in the trip, (it should be available in account page in future).
Admin can also see all users in the trip in admin page.
