### ISSUE TITLE
Facebook and Twitter Integration for Sharing 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#13]
Through the Hackathon app that you guys have made you have the Twitter button.

@freindst can it integrate yet? Can people share through it or is it just the button?

Obviously Facebook is the next one to add too and actual sharing capability is essential

**Comment by duncangraham** [comment]
I think adding sharing functionalities makes sense on the individual bus pages and most importantly, on the confirmation page (along with clearly communicating that the more people that buy tickets, the cheaper the bus will be)

**Comment by freindst** [comment]
@duncangraham Do you mean confirm page of pledging a trip or create a trip?

**Comment by markstm17** [comment]
@duncangraham definitely on the confirmation page. "Now share with friends so YOUR price drops!"

@freindst Both, but specifically for "pledging" for a trip right now. At least for Dave next Sat (25th), creating a trip will be created by me/us.


For create a trip, it should be something like "Invite and tell friends so wheels on the bus can go round and round" (Obviously message can be improved)

**Comment by freindst** [comment]
although not perfect, social media button is on live. #111
