### ISSUE TITLE
Make Email and Phone # Fields Required 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#14]
Making the fields when signing up for the first time for email and Phone Number required

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/8686330/ff8174c2-2a4a-11e5-8aed-93469fc44c24.png)

**Comment by freindst** [comment]
i think we will make either email or phone number at least one required field before complete register process. Someone may not willing to share their phone number with us.
We will inform them with both methods.

**Comment by freindst** [comment]
email is a compulsory field as register username. I am closing this issue.
