### ISSUE TITLE
Automated Email Notifications

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#18]
Something like these for their specific actions:

 - [x] Pledging for a trip: "You have pledged to join this trip, keep sharing with friends to lower the cost!"

 - [x] Threshold hit-Switching from potential to real/actual bus: "Your potential trip is now LIVE! There are enough people to make this trip possible! Keep sharing so it's cheaper for you and for everyone else !"

 - [x] 48 hours before event: "You can no longer Back out of this event, you're locked in! But the price can still go down! Keep Sharing!"

**Comment by freindst** [comment]
Good idea

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9255836/833fc822-41b1-11e5-8eca-cf0080ca31bc.png)

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9255842/9470ef9a-41b1-11e5-8bc3-0e57c668023a.png)

**Comment by freindst** [comment]
48 hours before event:
I think it is too annoyed if we sent emails to users only to tell they that they cannot quit. Instead, I make cancel pledging button disabled at user account page.
![image](https://cloud.githubusercontent.com/assets/13219475/9259141/e3fd6e9a-41c4-11e5-8bfe-6d3d43d39129.png)
