### ISSUE TITLE
Allow 1 user to sign up multiple people/friends for a bus trip

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#21]
Allow @duncangraham to sign up @freindst and @mlitman so friends can get spots together

**Comment by freindst** [comment]
I doubt it is the right way to use gitbub  in different account, our changes to code will not be merged together when we are both working on same project

**Comment by markstm17** [comment]
I meant for signing up for a bus trip. Sorry if it was confusing, I meant to show the example that Duncan can sign Blade and Mike up for the "Dave Matthews Bus"


If Duncan is paying for three spots (Himself, Blade and Mike) then there are simply drop down menus/fields for Duncan to put Blade and Mikes name in


Does that make sense @freindst ?

**Comment by freindst** [comment]
okay. It shall be done when i change the logic. It requires a bit more effort.

**Comment by markstm17** [comment]
If thats the case, don't worry about it for the first bus then

**Comment by markstm17** [comment]
I'll clear it as a milestone for the Dave bus, if there is time to get to it, then great!

If not we can focus on that after this first trip
