### ISSUE TITLE
While Pledging to a Trip, the Organizer will need first and last name instead of just their email

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#60]
Current view:

![screen shot 2015-08-02 at 11 18 34 am](https://cloud.githubusercontent.com/assets/11848699/9026955/450fa722-3908-11e5-8683-32601c364e5e.png)

**Comment by duncangraham** [comment]
looking good @freindst 

is there a view for admins to see the whole list of people on a bus?

**Comment by freindst** [comment]
duplicate #72
