### ISSUE TITLE
Pause the ability for anybody else to “Create a Trip” (until After Aug 22nd)

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#61]
![image](https://cloud.githubusercontent.com/assets/11848699/9030215/4b9808c0-3965-11e5-884b-a26ea77909da.png)

**Comment by duncangraham** [comment]
I'll hook the create trip button up to a view that lets people signup for a mailing list. Then once we allow people to create trips I can email them all.

**Comment by freindst** [comment]
duplicate: #72
