### ISSUE TITLE
Have better visuals on home screen

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#65]
@duncangraham You threw together a perfect (in my opinion) first bus/trip/event/image and shared it with us last week. Listed below

**Comment by duncangraham** [comment]
yea, I'll make this happen this week. Gotta work with the copywriting a bit, and the general design. I'll focus on this today though.

**Comment by markstm17** [comment]
Sounds good. Really looking forward to it @duncangraham

**Comment by duncangraham** [comment]
<img width="1390" alt="screen shot 2015-08-05 at 10 44 49 am" src="https://cloud.githubusercontent.com/assets/865298/9093133/0b73c85a-3b5f-11e5-9500-7439489a47e1.png">

this happened!

**Comment by markstm17** [comment]
It looks great! The only thing is that it still cuts off the top and bottom parts on the master website right now

![screen shot 2015-08-05 at 1 16 21 pm](https://cloud.githubusercontent.com/assets/11848699/9093895/61ff18f4-3b74-11e5-9903-023246022cc5.png)

**Comment by markstm17** [comment]
Just take a look into that if you can/don't mind @duncangraham
