### ISSUE TITLE
BrainTree Doesn't Work

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#67]
@freindst let me know if it is because we are still using "Sandbox" still. 

But I tried inputting and saving my credit card info on two separate cards and it gave me a try again screen

**Comment by freindst** [comment]
Here is what I found on Braintreepayment. In fact, I am using **4111 1111 1111 1111** for testing all the time.
[The sandbox environment only accepts test credit card numbers. The following card numbers may be used to trigger specific responses:]
(https://developers.braintreepayments.com/javascript+node/reference/general/testing)
