### ISSUE TITLE
Details Needed for Creating Trip as an Organizer

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#7]
![image](https://cloud.githubusercontent.com/assets/11848699/8684618/28eec0fa-2a3f-11e5-9405-39b931c5a761.png)

**Comment by markstm17** [comment]
If private trip, then Organizer needs to be directed to ability to text or share link with contacts through Mobile Phone or group through Social Media

**Comment by freindst** [comment]
Right now, I have add additional fields in create trip page.
Web app will read the user's ID, and take the user as default organizer. Then, the organizer's name, phone number, email will be display automatically.
I also add a field named with isSMSAllowed, to identify whether the organizer allow other contact him/herself with SMS message.

I think for sharing link, I will add a trip manage page for organizer. He can browse trip created by himself, and have buttons for social media sharing.(this hasn't been done)

**Comment by markstm17** [comment]
@freindst awesome. This is definitely essential. Can you make it a priority for the sharing to be integrated  from the people who join a trip (For our first official trip: Dave Concert on July 25th) so they can share with their friends online?

**Comment by freindst** [comment]
Okay. I will get down to it after I finish my current work. I am managing how to make template work and related issues. As your former comment, organizer can choose either one in two existed template when creating trip.

**Comment by markstm17** [comment]
@freindst what do you mean either one or two Blade?

**Comment by freindst** [comment]
Sorry  i mean choose one template

**Comment by markstm17** [comment]
For Buffett, it is NOT essential to change all this right now, but there are a few things on Create Trip page for an Organizer that should be changed. Take a look @duncangraham and @freindst and let me know your thoughts 


To get bare minimum info, all we need is this:

1. Trip Name (Unique to whatever organizer picks)

2. Event and Date/Dates of rental (Just date, no time. Drop down Calendar menu)
----Example: Brewers game 9/17/2015
----Example: Jimmy Buffett 8/22/2015

3. Pick Up Address
4. Pick Up Time

5. Destination Address

6. Drop off Address (If different)
7. Drop off Time

8. Number of passengers

9. Food or beverage (Often adds $50-$100 to cost)

10. Special conditions/Description/Comments

**Comment by markstm17** [comment]
For Drop off Address we can have two check boxes

Same

or

Different. If it is different let organizer input new address(es)

**Comment by freindst** [comment]
I think there is no need to have a destination address. For example, if the bus will drop people at Milwaukee airport, there is no difference between drop off address with destination address, unless you want to specify event address.

**Comment by markstm17** [comment]
What the focus is that we are creating is an improved process for organizing private, rented charter and social events for groups of people. 

This can range from a sports game, concert, wedding, bachelor or bachelorette party, trip to casino, tour of a city, class reunion, etc... Really anything 

The destination(s) is where the group is going, but the group needs to get dropped back off at the original  location, or multiple drop off locations (sometimes there are one way trips, but it is rare)

**Comment by freindst** [comment]
I have no problem with your comments. In this case, would you please give me a example of the trip you will organize on 8/22.
Tell me all information you think is necessary to fill into the trip. I am working on the create trip form right now, and I hope I can settle this problem down once and for all.

**Comment by markstm17** [comment]
Pick Up Address: 336 River Bluff Circle, Oconomowoc WI 53066
Multiple Pick Up addresses? (No)

Destination: Alpine Valley Music Amphitheater, East Troy Wisconsin 


Drop Off Address(es): 1. Park and Ride off Interstate 94
2. 336 River Bluff Circle, Oconomowoc WI 53066

**Comment by markstm17** [comment]
Does that make sense @freindst ?

**Comment by freindst** [comment]
No problem

**Comment by markstm17** [comment]
That's an example of having multiple drop off locations.

With these charter trips, there is a pick up location(s) and a destination(s) (which is the event or reason for renting bus in first place for large group of people)


Then AFTER the event there is a drop off location(s)
It could change or there could be more then one drop off location


So drop off location is after event, and destination is during event

**Comment by freindst** [comment]
It may take a while for me to build it. It is much more complicated.

**Comment by markstm17** [comment]
For now, DO NOT worry about multiple pick up or drop off locations (MVP)


I just was explaining that we need a Destination Field (For the sake of it now, the pick up and drop off locations will be the SAME)

**Comment by markstm17** [comment]
Does that make sense @freindst

**Comment by freindst** [comment]
Is the destination the same as event address?

**Comment by markstm17** [comment]
I just wanted to clarify that the Drop off location is after the event


The destination location is during the event


(think of going from Milwaukee to Green Bay for a Packers game @freindst)


---YES to your above question Blade

**Comment by markstm17** [comment]
It will get more complicated and we can build off of that in the future (for multiple pick up and drop off locations), but lets keep it simple now.


I just wanted to clarify we need a Destination field (or event address field) to input address @freindst

**Comment by freindst** [comment]
Okay. In that case, I just make a new event address field. In future, we can add multiple pick up address and drop off address

**Comment by markstm17** [comment]
Perfect, that is all we need now. Sorry for making it so confusing. We literally have 30 comments on this issue hahaha @freindst

**Comment by freindst** [comment]
Does it looks okay to you? @markstm17 
![image](https://cloud.githubusercontent.com/assets/13219475/9092074/72c4232e-3b69-11e5-83e8-428b3fb032e9.png)

**Comment by markstm17** [comment]
Yes, it looks great but I do Agree with @duncangraham and what we talked about on #76 


For Bus 1 above it should be the following:

1. Trip Name
2. Pick up and Drop off Address
3. Destination Address
4. Pick Up time
5. Final Drop off time
6. Expected number of passengers partying
7. Food and Beverage (Yes or No)


It is more of renaming them to clarify the action of the info needed.

Again in regards to the pricing for me, all that really matters is the time rental. That (for the most part) gives me the dollar amount it will cost to rent bus for group

**Comment by freindst** [comment]
I will close this one and merge to #76
