### ISSUE TITLE
remove template creation from trip creation

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#71]
Users shouldn't have to create the dynamic pricing template themselves. Its way too confusing to expect them to do that. The dynamic pricing should be created and controlled/updated algorithmically.

<img width="1390" alt="screen shot 2015-08-03 at 12 02 59 pm" src="https://cloud.githubusercontent.com/assets/865298/9045415/d416d8e4-39d7-11e5-8d15-e7b8b639b420.png">

I think we should put this feature on ice till after jimmy buffet. Once we have buses running, this should be a top priority.

**Comment by freindst** [comment]
duplicate: #72
