### ISSUE TITLE
Administrator Managing page

### ISSUE THREAD

**Issue by freindst** [hivemindworks/Argo-Project-V0#72]
I am creating a admin page. It will contain those function: (any related issues will be merged here)
1.All trip lists 
   * Brief trip information and its organizer's name
   * Brief trip state:
      * waiting for approval(need admin to add pricing template)/approved
      * below minimum passenger number/above minimum passenger number to go
      * not departure(not yet for charge money)/left(ready for charge money)

2.click link will see details of the trip
   * detailed information of trips
   * organizer information
   * current passenger list in the trip
   * Trip control (add template, changing template, sending email to organizer, etc.)

3.other functions waiting to be added in future

**Comment by markstm17** [comment]
This will be good to be able to see, even for our first trip, with us being the administrators and the organizers.

**Comment by freindst** [comment]
Added a admin page by clicking button on top of the page(temporary, as we cannot distinguish admin from common user)
- [x] Admin page shows brief information for admin to know the status of the trip, such as current price, departure time, and if the trip has a template, if the trip has reached the minimum required user.
- [ ] Trip is now clickable, and it will go to a new screen to manifest the trip, like add template, charge the price, etc. (not finished completely)

**Comment by freindst** [comment]
Click each trip will go to a new page to browsing detailed trip information.
- [x] update template button
- [ ] insert/update template function
- [x] Charging trip link

**Comment by freindst** [comment]
all functions have been implemented

**Comment by markstm17** [comment]
Is there any way we can set the admin page button to a specific email where only we can access it? 

I have read all these closed issues, but I still think it could be a problem for users to click in there

**Comment by markstm17** [comment]
It seems like the only way to pledge for a trip is through the admin page. 


Any chance we can get better flow for that?

**Comment by markstm17** [comment]
@duncangraham / @freindst

**Comment by freindst** [comment]
It is not my design. It seems that @duncangraham has merged trip page into admin page. I will separate them again.

**Comment by freindst** [comment]
Make trip list page back by click "current trips" button on top of the page
![image](https://cloud.githubusercontent.com/assets/13219475/9090705/6bd13b0e-3b61-11e5-9b77-e6400b9ff6b8.png)

**Comment by duncangraham** [comment]
@freindst yea I merged them because with the updates to the home page I took off the trip list.

for the buffet concert I imagine we'll be sending around the actual trip page

e.g. argobus.com/trip/100019929

**Comment by markstm17** [comment]
Correct @duncangraham 

Having a specific link for the actual trip page

We still want to process if typing in argobus.com to find the current trip (Buffett) to be easy too though. For that let's have a current Trips tab instead of it on admin page

**Comment by freindst** [comment]
I am confused by your comments.
First of all, I guess in the beginning the idea that our home page shows all trips is not bad. Now, our home page displays only a image. Shall we go back to trip list?
Another thing is having a current trips button above is also okay, as user will always goes to trip list to browse trips.
Third, if we have a page(argobus.com/trip/100019929), does it mean after user clicking a trip in trip list,  he/she will be leading to this page? The page will give option to be pledged?

**Comment by markstm17** [comment]
First: But for this first trip, there will only be one trip (Buffett) So there really isn't a trip list.

Second: So once logged in, then the user can go to current trips (which will only have our one bus (Buffett))

And Third: YES

Make sense @freindst ? What are your thoughts?

**Comment by freindst** [comment]
Of course it will be convenient(direct?) when there is only one trip, and user shall lead to that trip directly. However, why we have to create more logic branches in codes?
For example, let's compare the procedures when there are two trips and only one trip following your logic:

 Step | Two Trips | One Trip
------------ | ------------- | -------------
1 | user log in | user log in
2 | view the trip lists | -------------
3 | determine and select one trip | -------------
4 | jump to a page to pledge the trip | jump to the page to pledge the trip
5 | provide payment info | provide payment info
6 | finish pledging | finish pledging

So, we can see that if following your logic(one trip is not a trip list), it creates a new logic which bypasses two procedures in pledging a trip. In my opinion, there is no need to distinguish if there is only one trip, or there are multiple trips.

**Comment by duncangraham** [comment]
Below is how I think the flow could be executed best. we should move forward expecting that there will be multiple trips, though the flow shouldn't change based on how many trips are active. 

Step | Two Trips | One Trip
------------ | ------------- | -------------
1 | view the trip lists | view the trip lists
2 | determine and select trip | determine and select trip
3 | user log in or sign up | user log in or sign up
4 | jump to a page to pledge the trip | jump to the page to pledge the trip
5 | provide payment info | provide payment info
6 | finish pledging | finish pledging

**Comment by freindst** [comment]
Original problem has been solved. business screen flow shall be discuss in #112.
