### ISSUE TITLE
Admin Page Link

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#74]
When clicking on Details for the link this is what it directs me too

![screen shot 2015-08-04 at 8 35 05 am](https://cloud.githubusercontent.com/assets/11848699/9061845/0c944be6-3a84-11e5-9c9a-c8af4099be01.png)

**Comment by freindst** [comment]
Sorry, I haven't finished it yet. It will be done in an hour
duplicate #72
