### ISSUE TITLE
Editing Current Trip 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#75]
Not Essential for Buffett, because nobody else is going to be creating or editing a trip, but how do we edit an existing trip?

I'm getting $null because I think I inputted $60 instead of the number 60

![screen shot 2015-08-04 at 8 40 44 am](https://cloud.githubusercontent.com/assets/11848699/9061942/b5c70b40-3a84-11e5-9ef4-d3102657a985.png)

**Comment by freindst** [comment]
We will add restriction and validation to the input box later. Here, as the current price datatype is number, it cannot hold "$60" instead of "60", so it shows null, which in fact there is nothing in the field right now.

**Comment by markstm17** [comment]
@freindst I just deleted and then made a new trip (The Jimmy Buffett Test) and I still received $null. Can you look into that? I think it has to do with the template, because I did not manually input a starting amount, I used the drop down menu that the create trip page provides

**Comment by freindst** [comment]
Organizer click his account will be able to update trip information.
Everyone's own account page can: 
 1. update personal information
 2. update or cancel own trips
 3. cancel pledged trip
