### ISSUE TITLE
email notification functions

### ISSUE THREAD

**Issue by freindst** [hivemindworks/Argo-Project-V0#79]
Added a sandgrid method.
Now argo will send email to all users who has pledged the trip if price changes.
Still in testing.

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9075809/0149d034-3adf-11e5-9593-8adbfce5b384.png)
finished

**Comment by markstm17** [comment]
This is awesome! I'm excited to play around with this function

**Comment by markstm17** [comment]
To make it easy right now, lets go off the "template" we have talked about Blade (won't let me tag you??)


Can we decrease it every 10 people by $10 starting at $60


0-10 $60
11-20 $50
21-30 $40
31-40 $30
41-50 $20

**Comment by freindst** [comment]
Price changing notification is whenever the price changes (because of passenger increasing), each user in the trip will get a email which tells how much the price goes down.
So, if the template is:
0-10 $60
11-20 $50
21-30 $40
31-40 $30
41-50 $20
notification is $10 drop
if template is
0-1: $60
2-2  $59
3-3  $58
....
notification is $1 drop each time
