### ISSUE TITLE
create trip progress

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#80]
I've been making changes to the create trip page. I was going to be working on the reservation process but I had to go through this first and got sidetracked. This is the side by side.

old
--
![create](https://cloud.githubusercontent.com/assets/865298/9078549/d69c0b3e-3af4-11e5-9870-9bcd43a1c7cd.png)

new
--
<img width="1392" alt="screen shot 2015-08-04 at 9 57 30 pm" src="https://cloud.githubusercontent.com/assets/865298/9078548/d11257f4-3af4-11e5-82ff-49f9a4336d96.png">

You can see I've removed most of the fields and laid things out so everything is above the fold. 

@freindst what is the maximum passenger field for?

**Comment by freindst** [comment]
It is not that important. At the beginning, I think a bus has a capacity, and that is the maximum passenger number.

**Comment by freindst** [comment]
Where is the event date, name, description?

**Comment by markstm17** [comment]
Please read #7 The last comment I put yesterday should have all that info included on this page. There are a total of 10 things


I'll need to have the ability to describe details for the group so they know if to bring own food and drinks, if it includes parking, etc... what is included with the price

**Comment by freindst** [comment]
I think it can be filled in description part. Or I can add a new field in database, like comments or additional information.

**Comment by duncangraham** [comment]
cc @freindst 

1. the event date can be figured out by parsing the pick up time. 
2. the trip name should describe the event.
3. the description doesn't seem necessary. If the trip name is made well, it should be the only description needed.

**Comment by freindst** [comment]
Until you have made a final conclusion with @markstm17 , please remain what it looks like right now.
I stay neutral. There is no much differences whether add or delete any fields as long as the user is satisfied.

**Comment by duncangraham** [comment]
at this point, this ticket is a duplicate of #76 I'll post updates there
