### ISSUE TITLE
Reading home page labels with background (See Picture)

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#83]
![screen shot 2015-08-05 at 8 54 01 am](https://cloud.githubusercontent.com/assets/11848699/9087342/aa7b1b52-3b4f-11e5-9315-34a0b335382f.png)

**Comment by freindst** [comment]
What do you mean by it? Is it cool?

**Comment by markstm17** [comment]
Sorry, should be more descriptive. You can't read the entire Argo and the sign up and the log in because it is white font on the white boarder. Let's make it all Green

**Comment by markstm17** [comment]
Also, small side note @duncangraham festival is spelt wrong. you forgot the i

**Comment by freindst** [comment]
Added style to the login/signup/account/logout button. Also, "festival" ><
![image](https://cloud.githubusercontent.com/assets/13219475/9090620/f5a83662-3b60-11e5-9a9d-197aee04f3fe.png)
![image](https://cloud.githubusercontent.com/assets/13219475/9090647/1b046e12-3b61-11e5-9739-159472f33096.png)

**Comment by duncangraham** [comment]
adding

```
background-size: cover;

fixes the visual bug. added that, rather than changing the button styles.

**Comment by duncangraham** [comment]
dammit. buttons were already changed, so now I'm changing them back

**Comment by duncangraham** [comment]
The new style focuses the attention on creating a trip, and removes the admin button.

you can still reach the admin endpoint by navigating to /admin. 

@markstm17 we should talk about goals as they relate to this page. I would argue that the goal now should be getting users reserving seats (not making their own buses). If this is the case then I can switch the CTA to the current bus list. closing this for now though

current
--
<img width="1390" alt="screen shot 2015-08-05 at 3 37 16 pm" src="https://cloud.githubusercontent.com/assets/865298/9099703/df9a4406-3b87-11e5-84bc-90f60915d8b5.png">

new
--
<img width="1390" alt="screen shot 2015-08-05 at 3 36 51 pm" src="https://cloud.githubusercontent.com/assets/865298/9099697/d3bd45ac-3b87-11e5-95c7-39e0db0ceeef.png">

**Comment by markstm17** [comment]
@duncangraham for Buffett that is 100% the goal. I'll need to start educating "organizers" that reach out to me through partybybus.com , word of mouth, contacts, selling, etc... to the process of organizing a bus through Argo when the time comes.

But I agree with the current goal is getting users to reserve spots on the buses we organize through Argo
