### ISSUE TITLE
admin button should only appear if user role === admin

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#84]
<img width="1390" alt="screen shot 2015-08-05 at 12 22 09 pm" src="https://cloud.githubusercontent.com/assets/865298/9095535/9d76ff8a-3b6c-11e5-8606-c74f60e1ecf5.png">

the admin button shouldn't show up by default. if I am an admin, then it should show up. and I think moving the admin functionality to the account page makes more sense. 

so the account page will have user info and trip history. If the user is an admin, then there will also be an admin section on the account page for that functionality.

**Comment by freindst** [comment]
duplicate #43

**Comment by markstm17** [comment]
Agreed @duncangraham and yes I know @freindst is on same page there too. We have discussed this.

**Comment by duncangraham** [comment]
cool, closing
