### ISSUE TITLE
Current Users Going Edit 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#89]
![current users going](https://cloud.githubusercontent.com/assets/11848699/9104334/e8e0d766-3bd0-11e5-9fed-bc17539e9289.png)

We can literally go through lots of different ideas/options/creative/funny/quarky ways to get our message across. This is where Branding starts to come in @duncangraham and @freindst 

I think we should change the four lines of Black Bold Capital Letters to something of this nature:

"Hey you! I'm talking to you! Yeah you, you just pledged! First off pat yourself on the back. Now do as all good pledges do and go recruit some more pledges to lower your trips (Instead of Trip, maybe autofill Jimmy Buffett Extravaganza or whatever trip name is) fare/cost/ticket price (whatever you wanna put in). Share with friends and you'll be rewarded with memories and thicker wallets and purses"

Then have Facebook and Twitter Integration 

Then maybe put a space or two between the message to "sell" and then say Current Trip Attendees/Partiers/Argoers/ include:

Then show list of all names

**Comment by markstm17** [comment]
Lots of comments that new users who sign up don't like seeing other people's emails on this page @duncangraham and @freindst 


I'll put a ticket together showing all the comments from the users who have used it through Facebook in a minute

**Comment by freindst** [comment]
easy to fix

**Comment by duncangraham** [comment]
yea, seeing all the emails is bad (unless you're an admin).

A feature that's a nice to have is a button that says 'Connect with Facebook to see friends that are attending'

Once people have connected an account to FB we can use that connection in all sorts of ways.

**Comment by markstm17** [comment]
Is there any way we can get this updated and have the social media component ready for Buffett or do you want to test it first @duncangraham ?

**Comment by markstm17** [comment]
For this first trip, can we edit the bold message to this?

"Hey you! I'm talking to you! Yeah you, you just pledged! First off pat yourself on the back. Now do as all good pledges do and go recruit some more pledges to lower your trips (Instead of Trip, maybe autofill Jimmy Buffett Extravaganza or whatever trip name is) fare/cost/ticket price (whatever you wanna put in). Share with friends and you'll be rewarded with memories and thicker wallets and purses"

Can we also not allow the new pledge to read the emails of everyone else

Lastly, can we integrate Facebook/Twitter to Share as an option?

**Comment by freindst** [comment]
1. Do you mean that we send such an email to the user?
 2. Yes.
 3. I will work on it today.

**Comment by markstm17** [comment]
1. Yes, we need to have a confirmation email to all users saying they have successfully pledged to the trip

And sounds good for the other two points 


I think I have confused myself with #90 and #91 as well.

I think part of the user experience should be fun quarky things. Would it take long to implement the following? (Having three separate email confirmations to change up the message to the 30-50 people on the bus)

1. Did you know that Jimmy Buffett was born on December 25th, 1946? It may be August 22nd, but it sure feels like Christmas. Share with friends and you'll be rewarded with memories and thicker wallets and purses

2. If we couldn't laugh, then we'd all go insane. If we couldn't use Argo, then we'd have no way to save money. Share with your friends so there are many more laughs then insane people

3. 

---Does this take a long time to implement? It's not really important for the first trip, but it goes with how I'd like to brand this moving forward

**Comment by freindst** [comment]
If you mean that different user may receive one in one of these three messages, I think using a random function can make it. It will not take long to finish it.

**Comment by markstm17** [comment]
Okay sounds good @freindst That's awesome

@duncangraham these three email messages are what I just put together this morning, tailoring it specifically to Buffett fans, some of his song quotes and the user experience of being at a concert of his. This goes in hand with

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9230432/d8abb20a-40e7-11e5-950b-dbcb4b05a3ba.png)
Randomly pick one of the line and add to main body.

**Comment by markstm17** [comment]
@freindst Awesome!


Any way we can change the message (the one you put together for the example) on this confirmation screen after pledging (through argobus.com) to the "Hey you" comment and paragraph? 

----"Hey you! I'm talking to you! Yeah you, you just pledged! First off pat yourself on the back. Now do as all good pledges do and go recruit some more pledges to lower your trips (Instead of Trip, maybe autofill Jimmy Buffett Extravaganza or whatever trip name is) fare/cost/ticket price (whatever you wanna put in). Share with friends and you'll be rewarded with memories and thicker wallets and purses"

![image](https://cloud.githubusercontent.com/assets/11848699/9230582/9a41ce0e-40e8-11e5-8728-77d9dc5f01ba.png)

**Comment by markstm17** [comment]
And then ALL of the confirmation emails that people get to their email accounts will vary based on the randomization of the three messages I commented earlier? 


Does that make sense @freindst ?

**Comment by freindst** [comment]
Yes

**Comment by markstm17** [comment]
I didn't see your entire first email edit an hour ago (the image didn't pop up when I was on my laptop)

I think we are on the same page, I'll post one more thing on #96 to hopefully make my back and forth between these issues easy to understand. Sorry for the confusion @freindst

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9230675/4a7789f8-40e9-11e5-88a5-a04a90bfe666.png)
This may be easier to view on your phone

**Comment by markstm17** [comment]
![image](https://cloud.githubusercontent.com/assets/11848699/9230746/b2019262-40e9-11e5-8514-aac00417b7c7.png)

"Hey you! I'm talking to you! You just pledged! First off, pat yourself on the back. Now do as all good pledges do and go recruit some more pledges to lower your trips ticket price! Share with friends and you'll be rewarded with memories and thicker wallets and purses"


@freindst The bold, all caps message you put in on this page after a pledge has pledge should be changed to the message I have above.

As far as the three different sendgrid.net email notifications, they should be randomly emailed to users in their confirmation email (Referring to #96 on our tickets on Git)


Sorry for the constant confusion, let me know if that makes sense now

**Comment by freindst** [comment]
Okay.

**Comment by markstm17** [comment]
Is it clear now @freindst ? Sorry for confusing and overlapping these two issues. Completely my fault. Just want to make sure we are on the same page now

**Comment by freindst** [comment]
If you are talking about two different subjects (like this one, one is view on webpage, another one is email notification) , it is better to discuss in different issues. (open another one)

**Comment by markstm17** [comment]
Yes, this current ticket is view webpage and should be changed to the "Hey you" comment we have talked about.

Email notification/confirmation is #96 and I commented on that one too. Sorry for mixing up the separate issues

**Comment by freindst** [comment]
![image](https://cloud.githubusercontent.com/assets/13219475/9231138/20b2eb46-40ec-11e5-9a8c-99b2372c33fa.png)
How about it? "test" is the trip name

**Comment by markstm17** [comment]
Perfect @freindst That's exactly what I was talking about. That's great. Lets let @duncangraham give some feedback on the actual message that I put together (You as well Blade) and we can fine tune it and change the words/message if need be. 

But I like it @freindst , good work

**Comment by markstm17** [comment]
![screen shot 2015-08-12 at 12 30 02 pm](https://cloud.githubusercontent.com/assets/11848699/9231476/0c709a8c-40ee-11e5-915b-49d8d184e3ef.png)

I just downloaded 4 tickets for the Wisconsin Innovation Awards next Tuesday off of Eventbrite and these were the web screens that popped up directly after (As something to compare off of and relate too)

**Comment by markstm17** [comment]
![screen shot 2015-08-12 at 12 30 16 pm](https://cloud.githubusercontent.com/assets/11848699/9231528/40a633e8-40ee-11e5-8f12-f2d58c3a7efe.png)

Could easily be a new ticket you think so @duncangraham (Social Media/Sharing Ticket??)

**Comment by duncangraham** [comment]
This ticket was originally intended to track the removal of the list of emails (and maybe names?) from the trip page.

If that's been done, then feel free to close the ticket @freindst.

I think the copy on the confirmation page and the emails still need work, but that's not in the scope of this ticket. I'd like to get through the visual and email audits, then cut more tickets after those 2 master tickets have been completed.

_sidenote: I do like [your suggestions](https://github.com/hivemindworks/Argo-Project-V0/issues/89#issuecomment-130356532) Trev_

**Comment by freindst** [comment]
I would like to open another issue to track the progress of social media sharing.
So, I think I will close this one, just as what you @duncangraham said, this issue has completed mostly.
