### ISSUE TITLE
Email-Blade to Admin Example 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#90]
![email-blade](https://cloud.githubusercontent.com/assets/11848699/9104423/23ef46f2-3bd2-11e5-8ad0-82e36f5593a7.jpg)

For now this is fine. But I'm just thinking of the same quarkiness and fun that we bring to users to bring to the three of us and the others that join our team down the road. It's good to make this stuff happen earlier rather then later.

Email Templates that switch up over time and change based upon the day/month/whatever

Here are some examples: 

Email Address (whatever it is) is ready for an easy way to get organized! She/He is Argoing! Get it?
Email Address (whatever it is) is ready to help get 10-20 cars off the road. Can you help her/him out with that? 
Email Address (whatever it is) is ready to have fun. Period. 
Email Address (Whatever it is) is getting married. Take the stress off her and get the wheels rolling!
Email Address (whatever it is) is ready to pay $100 extra to puke tonight. He looks thirsty.

Examples off the top of my head. We can have a lot of fun with this as it builds. It is fine now, but it's on my mind and I wanted to share!

**Comment by freindst** [comment]
Maybe I cannot get your humor. This email is sent from system to admin, why it needs to be fun? I accept the idea what funny words may be a good style, but I don't like it. 
Besides, it is a minor issue. We can make it an update after we have fully established the business.
