### ISSUE TITLE
Home Page Edits 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#92]
![home page](https://cloud.githubusercontent.com/assets/11848699/9104634/8b12c79e-3bd4-11e5-8e35-390953c00224.png)

The only thing (which is very minor right now for first trip-doesn't need to be done, but wouldn't hurt) is to get a few pictures (3-5) that scroll and change from right to left instead of just the one picture

Go to Uber or Apple's Website (I'm assuming both @duncangraham and @freindst know exactly what I'm talking about)

**Comment by duncangraham** [comment]
axing this-- Uber and apple have multiple goals with their carousels. Right now we're focused on getting people to create buses and sign up for buses. Having a carousel wouldn't make the page stronger though it would distract from the main goals we're focused on. It would also pull my attention away from other pages that very much need work.
