### ISSUE TITLE
Home Page (Logged In) Edit/Addition/Customization 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#93]
This is definitely pre mature but I literally just thought of it.

When you log on and you're on your home screen, you (as the user/organizer) can upload 3-5 of their own personal photos that scroll right to left.

Only difference in picture is that I'm logged in

![home page logged in](https://cloud.githubusercontent.com/assets/11848699/9104728/79f26c02-3bd5-11e5-99fe-8ad48d016f52.png)

**Comment by duncangraham** [comment]
what would be the goal of this? would these photos show for just that user or for all argo users? if they show up for everyone then how do we make sure there isn't pornography, etc?

I think a similar idea is to tell people to use #ridewithargo or #argobus on instagrams, and then we can start getting those photos from instagrams API to add to the site.

**Comment by markstm17** [comment]
I like your idea better @duncangraham . Way Better hahaha

**Comment by duncangraham** [comment]
lets punt this and revisit it when we are trying to rapidly grow (rather than test)
