### ISSUE TITLE
Nice to Meet you Duncan 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#94]
![nice to meet you duncan](https://cloud.githubusercontent.com/assets/11848699/9104750/aa44c9fe-3bd5-11e5-9b44-8c148d03cc83.png)

I think this is self explanatory @duncangraham 

-Also could have a few templates for "Nice to Meetcha, Name"

**Comment by duncangraham** [comment]
yea, that was the goal. Gotta change it to get the logged in username

**Comment by markstm17** [comment]
Sounds good

**Comment by duncangraham** [comment]
@freindst this should show the users first name, rather than Duncan. this is the view in question: https://github.com/hivemindworks/Argo-Project-V0/blob/master/views/new_payment_method.jade
