### ISSUE TITLE
Trip Info While Pledging Edit 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#95]
![trip information while pledging](https://cloud.githubusercontent.com/assets/11848699/9104799/25772090-3bd6-11e5-8ff9-757e3dd1f3d6.png)

Don't want to repeat things.

I think this page needs more information about the trip (Like most of the details)

Also make this page a little bit more user friendly and FUN

**Comment by markstm17** [comment]
Again, I know we aren't Eventbrite and comparing to Eventbrite, but here is their info on the trip page. 

This is the page where we will want the price-ometer instead of the Early Bird Ticket prices/Standard Ticket Prices!

![organizer page](https://cloud.githubusercontent.com/assets/11848699/9104833/8597464e-3bd6-11e5-8187-f2bbf701d842.png)

**Comment by duncangraham** [comment]
this is a duplicate ticket of #66
