### ISSUE TITLE
Need Confirmation Email After Pledging 8/7/2015 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#96]
We have emails that let the attendees know when the price decreases, but a few people have asked if they did it wrong because they never received a confirmation email after they pledged for the bus

![11815934_10154090091092598_1869221626_n](https://cloud.githubusercontent.com/assets/11848699/9140606/28ecb884-3cf8-11e5-8e1c-272dce3c2637.jpg)

**Comment by freindst** [comment]
not a problem to fix

**Comment by markstm17** [comment]
I feel like we keep repeating some of the the things here and there is overlap with some of the issues/tickets.

This is what we were just talking about with #89 @freindst 

---Having confirmation email with three separate messages to the users for the user experience

**Comment by markstm17** [comment]
I think part of the user experience should be fun quarky things. Would it take long to implement the following? (Having three separate email confirmations to change up the message to the 30-50 people on the bus)

1. Did you know that Jimmy Buffett was born on December 25th, 1946? It may be August 22nd, but it sure feels like Christmas. Share with friends and you'll be rewarded with memories and thicker wallets and purses

2. If we couldn't laugh, then we'd all go insane. If we couldn't use Argo, then we'd have no way to save money. Share with your friends so there are many more laughs then insane people

3. Dancing Shoes, Check. Hula Skirt and coconut bra, check. It's 5 o'clock somehwere, check. That link helps you get to Margaritaville at a lower cost per person. Care to Share?

---Does this take a long time to implement? It's not really important for the first trip, but it goes with how I'd like to brand this moving forward

**Comment by freindst** [comment]
It has been accomplished in #89
