### ISSUE TITLE
Security Issues (https) 8/7/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#97]
I know I talked with both Mike and @duncangraham about this because I was curious and I didn't know the exact answer. Here are some screen shots from someone concerned about security @freindst , I just want all of us to be on same page, so let @freindst read and comment before closing

Also @duncangraham I know you mentioned converting to https. Let me know when you'll need a credit card if it costs $$$

![steve 1](https://cloud.githubusercontent.com/assets/11848699/9140868/e8aff7e8-3cf9-11e5-8675-4f7d7910b608.jpg)

**Comment by markstm17** [comment]
![steve 2](https://cloud.githubusercontent.com/assets/11848699/9140874/f7f6c1b4-3cf9-11e5-9af7-500c20b49cb4.jpg)

**Comment by markstm17** [comment]
![steve 3](https://cloud.githubusercontent.com/assets/11848699/9140878/fdce09c6-3cf9-11e5-9344-9c2e250dba34.jpg)

**Comment by freindst** [comment]
we have to find a way to know in how we can go through this payment process. I think we need to find all legal requirements in industry.

**Comment by markstm17** [comment]
@duncangraham I'm going to assign you to this. We should have this finished for Buffett-Changing to https

**Comment by duncangraham** [comment]
duplicate of #110 and I like #110 better.
