### ISSUE TITLE
User Feedback from Facebook 8/7/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#98]
I'm literally just going to post screen shots from comments from users. As more come in and comment, if they are applicable, I'll comment again

I'm assuming you'll want it to be a little bit more concise for particular issues Dunc, they are not in any order, but I want to do this so both @duncangraham and @freindst can read them, then we can break them up into REAL issues or tickets if any of us see anything or see real issues to address

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 17 01 am](https://cloud.githubusercontent.com/assets/11848699/9140911/5ce4a802-3cfa-11e5-8acb-f45d0b738529.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 17 16 am](https://cloud.githubusercontent.com/assets/11848699/9140916/658cc502-3cfa-11e5-8216-b111a0282748.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 17 33 am](https://cloud.githubusercontent.com/assets/11848699/9140919/6fb7c900-3cfa-11e5-94b2-a33ddee3573b.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 18 18 am](https://cloud.githubusercontent.com/assets/11848699/9140923/75dfbb3a-3cfa-11e5-8247-fa774eb6e421.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 18 55 am](https://cloud.githubusercontent.com/assets/11848699/9140931/82c4bdf0-3cfa-11e5-815f-f0f3cbb933af.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 19 12 am](https://cloud.githubusercontent.com/assets/11848699/9140943/8e91418a-3cfa-11e5-8359-2f6dc4b47691.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 23 54 am](https://cloud.githubusercontent.com/assets/11848699/9140949/94d0f388-3cfa-11e5-814e-d62ed19c81fa.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 51 55 am](https://cloud.githubusercontent.com/assets/11848699/9140984/d42a77e8-3cfa-11e5-9467-5f751f0abdf2.png)

**Comment by markstm17** [comment]
![screen shot 2015-08-07 at 11 52 08 am](https://cloud.githubusercontent.com/assets/11848699/9140988/dae421ec-3cfa-11e5-97d6-ff070e114080.png)

**Comment by freindst** [comment]
I decide to close this issue as I have collected all problem in #99
